# Generated by Django 4.2.6 on 2023-10-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_job_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='faculty',
        ),
        migrations.AddField(
            model_name='university',
            name='faculty',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
