# Generated by Django 4.2.6 on 2023-10-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_job_faculty_university_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
