# Generated by Django 4.2.6 on 2023-10-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_end',
            field=models.DateField(verbose_name='%Y-%m'),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_start',
            field=models.DateField(verbose_name='%Y-%m'),
        ),
    ]
